CREATE TABLE IF NOT EXISTS "CD_BocVo" (
	"id" INTEGER NOT NULL UNIQUE,
	"CaiDatCDBoc_ID" INTEGER,
	"DayVoTB" REAL NOT NULL,
	"InAn" TEXT NOT NULL,
	PRIMARY KEY("id"),
	FOREIGN KEY ("CaiDatCDBoc_ID") REFERENCES "CaiDatCDBoc"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "CD_BocLot" (
	"id" INTEGER NOT NULL UNIQUE,
	"CaiDatCDBoc_ID" INTEGER,
	"DoDayTBLot" REAL NOT NULL,
	PRIMARY KEY("id"),
	FOREIGN KEY ("CaiDatCDBoc_ID") REFERENCES "CaiDatCDBoc"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "CD_BocMach" (
	"id" INTEGER NOT NULL UNIQUE,
	"CaiDatCDBoc_ID" INTEGER NOT NULL,
	"NgoaiQuan" TEXT NOT NULL DEFAULT '1',
	-- (ghi số lần và số mét máy báo)
	"LanDanhThung" INTEGER NOT NULL,
	"SoMet" REAL NOT NULL,
	PRIMARY KEY("id"),
	FOREIGN KEY ("CaiDatCDBoc_ID") REFERENCES "CaiDatCDBoc"("id")
	ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "ThongTinCaLamViec" (
	"id" INTEGER NOT NULL UNIQUE,
	"Ngay" TEXT NOT NULL,
	"May" TEXT NOT NULL,
	"Ca" TEXT NOT NULL,
	"NguoiLam" TEXT NOT NULL,
	"ToTruong" TEXT,
	"QuanDoc" TEXT,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "DanhSachMaSP" (
	"id" INTEGER NOT NULL UNIQUE,
	"Ten" TEXT NOT NULL,
	"Ma" TEXT NOT NULL,
	-- 1 - Kg
	-- 0 - Mét
	"DonVi" TEXT NOT NULL,
	"KieuSP" TEXT NOT NULL,
	"DateInsert" DATETIME NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "TTThanhPham" (
	"id" INTEGER NOT NULL UNIQUE,
	"DanhSachSP_ID" INTEGER NOT NULL,
	"ThongTinCaLamViec_ID" INTEGER NOT NULL,
	"MaBin" TEXT NOT NULL,
	"KhoiLuongTruoc" REAL NOT NULL,
	"KhoiLuongSau" REAL NOT NULL DEFAULT 0,
	-- 1 - kg
	-- 0 - mét
	"ChieuDaiTruoc" REAL NOT NULL,
	"ChieuDaiSau" REAL NOT NULL,
	"Phe" REAL NOT NULL DEFAULT 0,
	"CongDoan" TEXT,
	"GhiChu" TEXT,
	"LastEdit_ID" INTEGER DEFAULT 0,
	"KLBanTran" REAL DEFAULT 0,
	"DateInsert" DATETIME,
	PRIMARY KEY("id"),
	FOREIGN KEY ("ThongTinCaLamViec_ID") REFERENCES "ThongTinCaLamViec"("id")
	ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY ("DanhSachSP_ID") REFERENCES "DanhSachMaSP"("id")
	ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "CD_KeoRut" (
	"id" INTEGER NOT NULL UNIQUE,
	"TTThanhPham_ID" INTEGER NOT NULL,
	"DKTrucX" REAL NOT NULL,
	"DKTrucY" REAL NOT NULL,
	"NgoaiQuan" TEXT NOT NULL,
	"TocDo" REAL NOT NULL,
	"DienApU" REAL NOT NULL,
	"DongDienU" REAL NOT NULL,
	PRIMARY KEY("id"),
	FOREIGN KEY ("TTThanhPham_ID") REFERENCES "TTThanhPham"("id")
	ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "CD_BenRuot" (
	"id" INTEGER NOT NULL UNIQUE,
	"TTThanhPham_ID" INTEGER NOT NULL,
	--  Đường kính/ Số sợi
	"DKSoi" REAL NOT NULL,
	"SoSoi" NUMERIC,
	-- Z
	-- S
	"ChieuXoan" TEXT NOT NULL DEFAULT 'Z',
	"BuocBen" REAL NOT NULL,
	PRIMARY KEY("id"),
	FOREIGN KEY ("TTThanhPham_ID") REFERENCES "TTThanhPham"("id")
	ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "CD_GhepLoiQB" (
	"id" INTEGER NOT NULL UNIQUE,
	"TTThanhPham_ID" INTEGER NOT NULL,
	"BuocXoan" REAL NOT NULL,
	-- Z
	-- S
	"ChieuXoan" TEXT NOT NULL DEFAULT 'Z',
	"GoiCachMep" REAL NOT NULL,
	"DKBTP" REAL NOT NULL,
	PRIMARY KEY("id"),
	FOREIGN KEY ("TTThanhPham_ID") REFERENCES "TTThanhPham"("id")
	ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "CaiDatCDBoc" (
	"id" INTEGER NOT NULL UNIQUE,
	"TTThanhPham_ID" INTEGER NOT NULL,
	-- 1 - OK
	-- 0 - NG
	"MangNuoc" TEXT NOT NULL DEFAULT '1',
	-- 1 - OK
	-- 0 - NG
	"PuliDanDay" TEXT NOT NULL DEFAULT '1',
	-- 1 - OK
	-- 0 - NG
	"BoDemMet" TEXT NOT NULL DEFAULT '1',
	"MayIn" TEXT,
	"v1" REAL,
	"v2" REAL,
	"v3" REAL,
	"v4" REAL,
	"v5" REAL,
	"v6" REAL,
	"Co" REAL,
	"Dau1" REAL,
	"Dau2" REAL,
	"Khuon" REAL,
	"BinhSay" REAL,
	"DKKhuon1" REAL NOT NULL,
	"DKKhuon2" REAL NOT NULL,
	"TTNhua" TEXT NOT NULL,
	"NhuaPhe" REAL NOT NULL,
	"GhiChuNhuaPhe" TEXT,
	"DayPhe" REAL NOT NULL,
	"GhiChuDayPhe" TEXT,
	"KTDKLan1" REAL NOT NULL,
	"KTDKLan2" REAL NOT NULL,
	"KTDKLan3" REAL NOT NULL,
	"DiemMongLan1" REAL NOT NULL,
	"DiemMongLan2" REAL NOT NULL,
	PRIMARY KEY("id"),
	FOREIGN KEY ("TTThanhPham_ID") REFERENCES "TTThanhPham"("id")
	ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "TTNVL" (
	"id" INTEGER NOT NULL UNIQUE,
	"TTThanhPham_ID" INTEGER NOT NULL,
	"DanhSachMaSP_ID" INTEGER,
	"BinNVL" TEXT NOT NULL,
	"KlBatDau" REAL,
	"CdBatDau" REAL,
	"KlConLai" REAL,
	"CdConLai" REAL,
	"DuongKinhSoiDong" REAL,
	"SoSoi" INTEGER,
	"KetCauLoi" REAL,
	"DuongKinhSoiMach" REAL,
	"BanRongBang" REAL,
	"DoDayBang" REAL,
	PRIMARY KEY("id"),
	FOREIGN KEY ("TTThanhPham_ID") REFERENCES "TTThanhPham"("id")
	ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY ("DanhSachMaSP_ID") REFERENCES "DanhSachMaSP"("id")
	ON UPDATE CASCADE ON DELETE CASCADE
);
